# Generated by Django 4.1.9 on 2023-06-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_contacts_options_alter_contacts_from_who_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="already_used",
            field=models.BooleanField(default=False),
        ),
    ]
