# Generated by Django 4.1.9 on 2023-06-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_contacts_already_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="failed",
            field=models.BooleanField(default=False),
        ),
    ]
